#!/bin/bash

### ANTLR
## ANTLR Tool
# alias antlr4='java -Xmx500M -cp ".:/usr/local/lib/antlr-4.9.3-complete.jar:$CLASSPATH" org.antlr.v4.Tool'
## C++ Generating Version
# alias antlr4c='java -Xmx500M -cp ".:/usr/local/lib/antlr-4.9.3-complete.jar:$CLASSPATH" org.antlr.v4.Tool -Dlanguage=Cpp'

args=("$@") # CLI Arguments
python3 build.py "${args[@]}"